# -*- coding: utf-8 -*-
"""BarChartsandAnalyzingDatafromCSVs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FGGahQmMyVQcy41rL1VSO8D-T2dK4y8
"""

import matplotlib
from matplotlib import pyplot as plt
import numpy as np
plt.style.use('fivethirtyeight')
import csv

ages_x = [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

dev_y = [38496, 42000, 46752, 49320, 53200,56000, 62316, 64928, 67317, 68748, 73752]
# Median Python Developer Salaries by Age

py_dev_y = [45372, 48876, 53850, 57287, 63016,
            65998, 70003, 70000, 71496, 75370, 83640]
            # Median JavaScript Developer Salaries by Age
js_dev_y = [37810, 43515, 46823, 49293, 53437,
            56373, 62375, 66674, 68745, 68746, 74583]

plt.bar(ages_x,dev_y,color='k',label="All devs")
plt.plot(ages_x,py_dev_y,marker='o',linewidth=3,label="Python")
plt.plot(ages_x,js_dev_y,linewidth=3,label="JavaScript")
plt.legend()
plt.show()

x_indices = np.arange(len(ages_x))
width=0.25

plt.bar(x_indices-width,dev_y,width=width,color='k',label="All devs")
plt.bar(x_indices,py_dev_y,width=width,label="Python")
plt.bar(x_indices+width,js_dev_y,width=width,linewidth=3,label="JavaScript")
plt.legend()
plt.show()

x_indices = np.arange(len(ages_x))
width=0.25

plt.bar(x_indices-width,dev_y,width=width,color='k',label="All devs")
plt.bar(x_indices,py_dev_y,width=width,label="Python")
plt.bar(x_indices+width,js_dev_y,width=width,linewidth=3,label="JavaScript")
plt.legend()
plt.xticks(ticks=x_indices,labels=ages_x)
plt.xlabel("Ages")
plt.ylabel("Median Salary (USD)")
plt.title("Median Salary (USD) by Age")
plt.show()

with open ('data.csv') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    row = next(csv_reader)
    print(row['LanguagesWorkedWith'].split(';'))#datacleaning

from collections import Counter
with open ('data.csv') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    language_counter = Counter()
    for row in csv_reader:
        language_counter.update(row['LanguagesWorkedWith'].split(';'))

print(language_counter.most_common(15))

languages=[]
popularity=[]
for item in language_counter.most_common(15):
    languages.append(item[0])
    popularity.append(item[1])

plt.barh(languages,popularity)
plt.xlabel("Popularity")
#plt.ylabel("Programming Languages")
plt.title("Most Popular Languages")
plt.tight_layout()
plt.show()

languages=[]
popularity=[]
for item in language_counter.most_common(15):
    languages.append(item[0])
    popularity.append(item[1])
languages.reverse()
popularity.reverse()
plt.barh(languages,popularity)
plt.xlabel("Popularity")
#plt.ylabel("Programming Languages")
plt.title("Most Popular Languages")
plt.tight_layout()
plt.show()

