# -*- coding: utf-8 -*-
"""ImageProcessingThroughMatPlotLib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4ti5sDGBLpO9bU8C96AxWvTz9z9Q2-N
"""

import numpy as np
import matplotlib.pyplot as plt

# fruit image
!gdown 17tYTDPBU5hpby9t0kGd7w_-zBsbY7sEd

# emma stone image
!gdown 1o-8yqdTM7cfz_mAaNCi2nH0urFu7pcqI

# dog image
!gdown 1ViZ9V5y5s9IRazM5ZaoWd_7p8QpJIJ92

img = np.array(plt.imread('fruits.png'))#imread is reading
plt.imshow(img)#imshow is showing

print('# of dims: ',img.ndim) # dimension of an image
print('img shape: ',img.shape) # shape of an image

"""```
3rd dimension for depth or RGB colour channel
```

```
So, a pixel [255, 0, 0 ] will be RED in colour.

A pixel [0, 255, 0] will be GREEN in colour.

A pixel [0, 0, 255] will be BLUE in colour.
```
"""

img_R = img.copy()

img_R[:, :, (1, 2)] = 0
plt.imshow(img_R)

img = np.array(plt.imread('emma_stone.jpeg'))
img_rotated = np.transpose(img,(1,0,2))#0,1,2 is org axis
plt.imshow(img_rotated)

rev_img = img[::-1,:,:]
plt.imshow(rev_img)

img_crop = img[100:500, 200:700, :]
plt.imshow(img_crop)

path = 'emma_face.jpg'
plt.imsave(path, img_crop)

img_blurr = img[::20,::20,:]
plt.imshow(img_blurr)

img_contrast=np.where(img>150,255,0)
plt.imshow(img_contrast)

img_negative_story=255-img
plt.imshow(img_negative_story)
path = 'emma_negativefullphoto.jpg'
plt.imsave(path, img_negative_story)

img_crop_BlackDress = img[500:, 100:, :]
plt.imshow(img_crop_BlackDress)

img_crop_BlackDress = img[500:, 100:, 0:1]
plt.imshow(img_crop_BlackDress)